package com.oneot.weather_forecast.query.mapper;

import com.oneot.weather_forecast.common.model.Forecast;
import com.oneot.weather_forecast.query.model.QueryForecast;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * Mapper interface for converting between Forecast and QueryForecast objects.
 * This interface uses MapStruct to generate the implementation for mapping
 * between the domain model (Forecast) and the query model (QueryForecast).
 */
@Mapper
public interface ForecastMapper {

    // Instance of the mapper generated by MapStruct
    ForecastMapper INSTANCE = Mappers.getMapper(ForecastMapper.class);

    /**
     * Converts a Forecast object to a QueryForecast object.
     *
     * @param forecast The Forecast object to be converted
     * @return QueryForecast The converted QueryForecast object
     */
    QueryForecast toQueryForecast(Forecast forecast);
}

