package com.oneot.weather_forecast.search.mapper;

import com.oneot.weather_forecast.common.model.Forecast;
import com.oneot.weather_forecast.search.model.SearchForecast;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * Mapper interface for converting between Forecast and SearchForecast objects.
 * This interface uses MapStruct to generate the implementation for mapping
 * between the domain model (Forecast) and the query model (SearchForecast).
 */
@Mapper
public interface ForecastMapper {

    // Instance of the mapper generated by MapStruct
    ForecastMapper INSTANCE = Mappers.getMapper(ForecastMapper.class);

    /**
     * Converts a Forecast object to a SearchForecast object.
     *
     * @param forecast The Forecast object to be converted
     * @return SearchForecast The converted SearchForecast object
     */
    SearchForecast toSearchForecast(Forecast forecast);
}

